'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Brain, CalendarDays, Check, ChevronLeft, ChevronRight, Edit3, Feather, FileText, Gamepad2, Home as HomeIcon, Menu, Moon, Pin, Plus, Search, Settings, Sparkles, Sun, Trash2, X } from 'lucide-react'

type View = 'home' | 'journal' | 'reflect' | 'insights' | 'games' | 'progress' | 'reports' | 'settings'
type Entry = { id: string; title: string; body: string; createdAt: string; updatedAt?: string; tags: string[]; mood: string; pinned?: boolean }

const navigation: { id: View; label: string; icon: typeof HomeIcon }[] = [
  { id: 'home', label: 'Home', icon: HomeIcon }, { id: 'journal', label: 'Journal', icon: BookOpen }, { id: 'reflect', label: 'Reflect with AI', icon: Sparkles }, { id: 'insights', label: 'Insights', icon: Brain }, { id: 'games', label: 'Activities', icon: Gamepad2 }, { id: 'progress', label: 'Calendar & progress', icon: CalendarDays }, { id: 'reports', label: 'Reports', icon: FileText }, { id: 'settings', label: 'Settings', icon: Settings },
]

export default function NeuroMirror() {
  const [view, setView] = useState<View>('home')
  const [dark, setDark] = useState(true)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [entries, setEntries] = useState<Entry[]>([])
  const [editorOpen, setEditorOpen] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [draft, setDraft] = useState('')
  const [draftTitle, setDraftTitle] = useState('')
  const [draftTags, setDraftTags] = useState('')
  const [draftMood, setDraftMood] = useState('')
  const [query, setQuery] = useState('')

  const filtered = useMemo(() => entries.filter(entry => `${entry.title} ${entry.body} ${entry.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [entries, query])
  const openEditor = (entry?: Entry) => { setEditingId(entry?.id ?? null); setDraft(entry?.body ?? ''); setDraftTitle(entry?.title ?? ''); setDraftTags(entry?.tags.join(', ') ?? ''); setDraftMood(entry?.mood === 'Unrated' ? '' : entry?.mood ?? ''); setEditorOpen(true) }
  const saveEntry = () => {
    const body = draft.trim(); if (!body) return
    const title = draftTitle.trim() || body.split(/[.!?]/)[0].slice(0, 60) || 'Untitled entry'
    const tags = draftTags.split(',').map(tag => tag.trim().replace(/^#/, '')).filter(Boolean).slice(0, 8)
    setEntries(current => editingId ? current.map(entry => entry.id === editingId ? { ...entry, title, body, tags, mood: draftMood || 'Unrated', updatedAt: new Date().toISOString() } : entry) : [{ id: crypto.randomUUID(), title, body, createdAt: new Date().toISOString(), tags, mood: draftMood || 'Unrated' }, ...current])
    setDraft(''); setDraftTitle(''); setDraftTags(''); setDraftMood(''); setEditingId(null); setEditorOpen(false); setView('journal')
  }
  const deleteEntry = (id: string) => setEntries(current => current.filter(entry => entry.id !== id))
  const togglePin = (id: string) => setEntries(current => current.map(entry => entry.id === id ? { ...entry, pinned: !entry.pinned } : entry).sort((a, b) => Number(Boolean(b.pinned)) - Number(Boolean(a.pinned))))

  return <main className={dark ? 'dark min-h-screen' : 'min-h-screen'}><div className="flex min-h-screen bg-background text-foreground">
    <aside className={`${mobileOpen ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-20 flex w-72 flex-col border-r border-border bg-card p-6 transition-transform lg:static lg:translate-x-0`}>
      <div className="flex items-center justify-between"><button onClick={() => setView('home')} className="flex items-center gap-3 text-left"><span className="flex size-10 items-center justify-center rounded-2xl bg-sage-soft text-sage"><Feather /></span><span><span className="block font-display text-xl">NeuroMirror</span><span className="text-[11px] uppercase tracking-[.18em] text-muted">your quiet space</span></span></button><button className="lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X /></button></div>
      <nav className="mt-12 flex flex-1 flex-col gap-1">{navigation.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => { setView(item.id); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition-colors ${view === item.id ? 'bg-sage-soft font-semibold text-sage' : 'text-muted hover:bg-background hover:text-foreground'}`}><Icon className="size-[18px]" />{item.label}</button> })}</nav>
      <div className="rounded-2xl bg-sage-soft p-4"><p className="font-display text-lg">Write → Reflect → Remember</p><p className="mt-2 text-xs leading-relaxed text-muted">Your writing belongs to you. NeuroMirror never invents entries or insights.</p></div>
      <button onClick={() => setView('settings')} className="mt-5 flex items-center gap-3 px-3 py-2 text-sm text-muted"><Settings className="size-4" />Preferences</button>
    </aside>
    <section className="min-w-0 flex-1"><header className="sticky top-0 z-10 flex h-20 items-center justify-between border-b border-border bg-background/90 px-5 backdrop-blur-md sm:px-8 lg:px-12"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu /></button><div className="relative hidden sm:block"><Search className="absolute left-3 top-2.5 size-4 text-muted" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search your journal..." className="w-64 rounded-full border border-border bg-card py-2 pl-9 pr-4 text-sm outline-none focus:border-sage" /></div></div><div className="flex items-center gap-3"><button onClick={() => setDark(!dark)} className="rounded-full p-2 text-muted hover:bg-card" aria-label="Toggle theme">{dark ? <Sun className="size-4" /> : <Moon className="size-4" />}</button><div className="flex size-9 items-center justify-center rounded-full bg-sand font-display text-sm">NM</div></div></header><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-12"><ViewContent view={view} entries={filtered} allEntries={entries} onWrite={() => openEditor()} onEdit={openEditor} onDelete={deleteEntry} onTogglePin={togglePin} onNavigate={setView} /></div></section>
  </div>{editorOpen && <Editor editing={Boolean(editingId)} title={draftTitle} setTitle={setDraftTitle} draft={draft} setDraft={setDraft} tags={draftTags} setTags={setDraftTags} mood={draftMood} setMood={setDraftMood} onClose={() => setEditorOpen(false)} onSave={saveEntry} />}</main>
}

function ViewContent({ view, entries, allEntries, onWrite, onEdit, onDelete, onTogglePin, onNavigate }: { view: View; entries: Entry[]; allEntries: Entry[]; onWrite: () => void; onEdit: (entry: Entry) => void; onDelete: (id: string) => void; onTogglePin: (id: string) => void; onNavigate: (view: View) => void }) {
  if (view === 'home') return <HomeView entries={allEntries} onWrite={onWrite} onNavigate={onNavigate} />
  const meta: Record<Exclude<View, 'home'>, [string, string]> = { journal: ['Your journal', 'A chronological archive of your thoughts.'], reflect: ['Reflect with AI', 'Use Gemini to ask gentle questions about words you actually wrote.'], insights: ['Insights', 'Optional observations generated only from your own entries.'], games: ['Activities', 'Small, optional exercises for attention and memory.'], progress: ['Calendar & progress', 'See exactly which days have entries and open them from the calendar.'], reports: ['Reports', 'Create a private summary when you have enough writing to make it useful.'], settings: ['Settings', 'Control your experience and your data.'] }
  const [title, description] = meta[view]
  return <><PageHeader title={title} description={description} action={['journal', 'reflect'].includes(view) ? <button onClick={onWrite} className="flex items-center justify-center gap-2 rounded-full bg-sage px-5 py-3 font-semibold text-white"><Plus className="size-4" />Write an entry</button> : undefined} />{view === 'journal' && <Journal entries={entries} onWrite={onWrite} onEdit={onEdit} onDelete={onDelete} onTogglePin={onTogglePin} />}{view === 'reflect' && <Reflect entries={allEntries} onWrite={onWrite} />}{view === 'insights' && <Insights entries={allEntries} />}{view === 'games' && <Activities />}{view === 'progress' && <Calendar entries={allEntries} onOpenJournal={() => onNavigate('journal')} />}{view === 'reports' && <Reports entries={allEntries} />}{view === 'settings' && <SettingsView />}</>
}
function PageHeader({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-sage">NeuroMirror</p><h1 className="mt-2 font-display text-5xl">{title}</h1><p className="mt-3 text-muted">{description}</p></div>{action}</div> }
function HomeView({ entries, onWrite, onNavigate }: { entries: Entry[]; onWrite: () => void; onNavigate: (v: View) => void }) { const latest = entries[0]; return <><PageHeader title="Welcome back." description="Make a little space for what is here today." action={<button onClick={onWrite} className="flex items-center justify-center gap-2 rounded-full bg-sage px-5 py-3 font-semibold text-white"><Plus className="size-4" />Write today&apos;s entry</button>} /><div className="mt-10 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl bg-sage-soft p-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-sage">Today&apos;s space</p>{latest ? <><h2 className="mt-3 font-display text-3xl">{latest.title}</h2><p className="mt-5 line-clamp-4 leading-relaxed text-muted">{latest.body}</p><button onClick={() => onNavigate('journal')} className="mt-7 flex items-center gap-2 text-sm font-semibold text-sage">Open your journal <ArrowRight className="size-4" /></button></> : <><h2 className="mt-3 font-display text-3xl">Nothing written yet</h2><p className="mt-5 max-w-xl leading-relaxed text-muted">This space will show your latest entry once you write one. There is no sample content here.</p><button onClick={onWrite} className="mt-7 flex items-center gap-2 text-sm font-semibold text-sage">Write your first entry <ArrowRight className="size-4" /></button></>}</div><div className="rounded-3xl border border-border bg-card p-7"><div className="flex items-center gap-2 text-sage"><CalendarDays className="size-4" /><span className="text-sm font-semibold">Your rhythm</span></div><p className="mt-5 font-display text-5xl">{entries.length}</p><p className="text-sm text-muted">{entries.length === 1 ? 'entry so far' : 'entries so far'}</p><button onClick={() => onNavigate('progress')} className="mt-8 flex items-center gap-2 text-sm font-semibold text-sage">Open calendar <ArrowRight className="size-4" /></button></div></div></> }
function Empty({ title, text, action, onClick }: { title: string; text: string; action?: string; onClick?: () => void }) { return <div className="mt-8 rounded-3xl border border-dashed border-border bg-card p-10 text-center"><BookOpen className="mx-auto text-muted" /><h2 className="mt-4 font-display text-2xl">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-muted">{text}</p>{action && <button onClick={onClick} className="mt-6 rounded-full bg-sage px-5 py-3 text-sm font-semibold text-white">{action}</button>}</div> }
function Journal({ entries, onWrite, onEdit, onDelete, onTogglePin }: { entries: Entry[]; onWrite: () => void; onEdit: (entry: Entry) => void; onDelete: (id: string) => void; onTogglePin: (id: string) => void }) { return entries.length ? <div className="mt-8 grid gap-4 md:grid-cols-2">{entries.map(entry => <article key={entry.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div className="h-1.5 w-12 rounded-full bg-sage" />{entry.pinned && <Pin className="size-4 text-sage" />}</div><p className="mt-5 text-xs text-muted">{new Date(entry.createdAt).toLocaleString()}{entry.updatedAt ? ' · edited' : ''}</p><h2 className="mt-2 font-display text-2xl">{entry.title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-muted">{entry.body}</p><div className="mt-4 flex flex-wrap gap-2">{entry.tags.map(tag => <span key={tag} className="rounded-full bg-sage-soft px-2.5 py-1 text-xs text-sage">#{tag}</span>)}</div><p className="mt-5 text-xs text-muted">{entry.body.split(/\s+/).filter(Boolean).length} words · {entry.mood || 'Unrated'}</p><div className="mt-5 flex gap-2 border-t border-border pt-4"><button onClick={() => onEdit(entry)} className="flex items-center gap-1.5 text-xs font-semibold text-sage"><Edit3 className="size-3.5" />Edit</button><button onClick={() => onTogglePin(entry.id)} className="flex items-center gap-1.5 text-xs text-muted"><Pin className="size-3.5" />{entry.pinned ? 'Unpin' : 'Pin'}</button><button onClick={() => onDelete(entry.id)} className="ml-auto flex items-center gap-1.5 text-xs text-muted hover:text-destructive"><Trash2 className="size-3.5" />Delete</button></div></article>)}</div> : <Empty title="No entries yet" text="Your journal is empty. Write something when you are ready and it will appear here and on the calendar." action="Write your first entry" onClick={onWrite} /> }
function Reflect({ entries, onWrite }: { entries: Entry[]; onWrite: () => void }) { const [result, setResult] = useState(''); const [busy, setBusy] = useState(false); const run = async (action: 'reflect' | 'analyze') => { if (!entries[0]) return; setBusy(true); setResult(''); try { const response = await fetch('/api/ai', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, text: entries[0].body }) }); const data = await response.json(); setResult(data.text || data.error) } catch { setResult('NeuroMirror could not connect right now. Your writing is still safe.') } finally { setBusy(false) } }; return <div className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl bg-lavender p-8"><Sparkles className="text-sage" /><h2 className="mt-8 font-display text-3xl">Let your writing lead.</h2>{entries[0] ? <><p className="mt-4 text-sm leading-relaxed text-muted">Gemini will use your latest entry to create a gentle, non-clinical response. It will not invent a history or diagnose you.</p><div className="mt-7 flex flex-wrap gap-3"><button disabled={busy} onClick={() => run('reflect')} className="rounded-full bg-foreground px-4 py-2 text-sm text-background disabled:opacity-50">{busy ? 'Thinking...' : 'Ask for reflection'}</button><button disabled={busy} onClick={() => run('analyze')} className="rounded-full border border-border px-4 py-2 text-sm disabled:opacity-50">Analyze language</button></div></> : <><p className="mt-4 text-sm leading-relaxed text-muted">Write an entry first. AI reflection becomes available after there is real writing to reflect on.</p><button onClick={onWrite} className="mt-7 rounded-full bg-sage px-5 py-3 text-sm font-semibold text-white">Write an entry</button></>}</div><div className="rounded-3xl border border-border bg-card p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-sage">Gemini response</p>{result ? <p className="mt-6 whitespace-pre-wrap text-lg leading-relaxed">{result}</p> : <p className="mt-6 text-sm leading-relaxed text-muted">{entries[0] ? 'Choose an action to receive a response grounded in your latest entry.' : 'There is nothing to respond to yet.'}</p>}</div></div> }
function Insights({ entries }: { entries: Entry[] }) { return entries.length ? <div className="mt-10 rounded-3xl bg-sage-soft p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-sage">Available after writing</p><h2 className="mt-3 font-display text-3xl">You have {entries.length} {entries.length === 1 ? 'entry' : 'entries'} to explore.</h2><p className="mt-4 max-w-2xl leading-relaxed text-muted">Insights will stay grounded in your own writing. Add more entries, then use Reflect with AI when you want an explainable Gemini observation.</p></div> : <Empty title="No insights yet" text="Insights need your writing first. Once you have entries, this page will show only observations grounded in those entries." /> }
function Activities() { return <div className="mt-10 rounded-3xl border border-border bg-card p-8"><Gamepad2 className="text-sage" /><h2 className="mt-5 font-display text-3xl">Activities are optional</h2><p className="mt-3 max-w-xl leading-relaxed text-muted">There are no fake scores or completed sessions. This space is ready for real activities when you choose to add them.</p></div> }
function Calendar({ entries, onOpenJournal }: { entries: Entry[]; onOpenJournal: () => void }) { const [month, setMonth] = useState(new Date()); const [selected, setSelected] = useState<string | null>(null); const year = month.getFullYear(); const monthIndex = month.getMonth(); const start = new Date(year, monthIndex, 1).getDay(); const days = new Date(year, monthIndex + 1, 0).getDate(); const byDay = new Map(entries.map(e => [new Date(e.createdAt).toDateString(), e])); const selectedEntry = selected ? byDay.get(new Date(selected).toDateString()) : undefined; return <div className="mt-10 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border border-border bg-card p-6 sm:p-8"><div className="flex items-center justify-between"><button onClick={() => setMonth(new Date(year, monthIndex - 1, 1))} className="rounded-full border border-border p-2" aria-label="Previous month"><ChevronLeft /></button><h2 className="font-display text-2xl">{month.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</h2><button onClick={() => setMonth(new Date(year, monthIndex + 1, 1))} className="rounded-full border border-border p-2" aria-label="Next month"><ChevronRight /></button></div><div className="mt-7 grid grid-cols-7 gap-2 text-center text-xs text-muted">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d => <span key={d}>{d}</span>)}{Array.from({ length: start }).map((_, i) => <span key={`blank-${i}`} />)}{Array.from({ length: days }, (_, i) => { const date = new Date(year, monthIndex, i + 1); const entry = byDay.get(date.toDateString()); return <button key={i} onClick={() => setSelected(date.toISOString())} className={`aspect-square rounded-xl text-sm ${selected && new Date(selected).toDateString() === date.toDateString() ? 'ring-2 ring-sage' : ''} ${entry ? 'bg-sage font-semibold text-white' : 'hover:bg-sage-soft'}`}>{i + 1}</button> })}</div><div className="mt-6 flex items-center gap-2 text-xs text-muted"><span className="size-3 rounded bg-sage" />Days with journal entries</div></div><div className="rounded-3xl bg-sage-soft p-8">{selectedEntry ? <><p className="text-xs uppercase tracking-[.18em] text-sage">Selected day</p><h2 className="mt-3 font-display text-2xl">{selectedEntry.title}</h2><p className="mt-4 line-clamp-6 text-sm leading-relaxed text-muted">{selectedEntry.body}</p><button onClick={onOpenJournal} className="mt-6 flex items-center gap-2 text-sm font-semibold text-sage">Open journal <ArrowRight className="size-4" /></button></> : <><CalendarDays className="text-sage" /><h2 className="mt-5 font-display text-2xl">{entries.length ? 'Choose a highlighted day' : 'Your calendar is empty'}</h2><p className="mt-3 text-sm leading-relaxed text-muted">{entries.length ? 'Select a green day to preview the entry written then.' : 'When you write, the entry date will be marked here automatically.'}</p></>}</div></div> }
function Reports({ entries }: { entries: Entry[] }) { return entries.length < 2 ? <Empty title="Not enough writing yet" text="Reports are intentionally unavailable until you have at least two real entries. That keeps summaries grounded instead of fabricated." /> : <div className="mt-10 rounded-3xl border border-border bg-card p-8"><FileText className="text-sage" /><h2 className="mt-5 font-display text-3xl">Ready for a private report</h2><p className="mt-3 text-muted">You have {entries.length} entries. Report generation can now be connected to the same Gemini workflow without adding sample data.</p></div> }
function SettingsView() { return <div className="mt-10 rounded-3xl border border-border bg-card p-8"><Settings className="text-sage" /><h2 className="mt-5 font-display text-3xl">Your data stays in this session</h2><p className="mt-3 max-w-xl leading-relaxed text-muted">Entries are held in the current app session for now. Gemini calls happen server-side through the configured GEMINI_API_KEY and the key never reaches your browser.</p></div> }
function Editor({ editing, title, setTitle, draft, setDraft, tags, setTags, mood, setMood, onClose, onSave }: { editing: boolean; title: string; setTitle: (v: string) => void; draft: string; setDraft: (v: string) => void; tags: string; setTags: (v: string) => void; mood: string; setMood: (v: string) => void; onClose: () => void; onSave: () => void }) { return <div className="fixed inset-0 z-30 flex items-end justify-center bg-black/40 p-0 sm:items-center sm:p-6"><div className="w-full max-w-2xl rounded-t-3xl bg-card p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-sage">{editing ? 'Edit entry' : 'New entry'}</p><h2 className="mt-2 font-display text-3xl">{editing ? 'Shape the note' : 'What is here today?'}</h2></div><button onClick={onClose} aria-label="Close editor"><X /></button></div><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Title (optional)" className="mt-6 w-full rounded-xl border border-border bg-background px-4 py-3 text-lg outline-none focus:border-sage" /><textarea autoFocus value={draft} onChange={e => setDraft(e.target.value)} placeholder="Start with one honest sentence..." className="mt-3 min-h-48 w-full resize-y rounded-2xl border border-border bg-background p-4 leading-relaxed outline-none focus:border-sage" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={tags} onChange={e => setTags(e.target.value)} placeholder="Tags, comma separated" className="rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none focus:border-sage" /><select value={mood} onChange={e => setMood(e.target.value)} className="rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none focus:border-sage"><option value="">Mood (optional)</option><option>Calm</option><option>Good</option><option>Okay</option><option>Heavy</option><option>Anxious</option></select></div><div className="mt-5 flex justify-end gap-3"><button onClick={onClose} className="rounded-full border border-border px-5 py-2 text-sm">Cancel</button><button onClick={onSave} disabled={!draft.trim()} className="flex items-center gap-2 rounded-full bg-sage px-5 py-2 text-sm font-semibold text-white disabled:opacity-50"><Check className="size-4" />{editing ? 'Update entry' : 'Save entry'}</button></div></div></div> }
